### ISSUE TITLE
Hi. I'm so sorry to bother you,i hope you can share me a Pretrained model link.but,in your code of NonUniformBlurKernelEstimation ,your Pretrained model link is not valid, can you provide a new link?

### ISSUE THREAD

**Issue by panyangh** [mackostya/ml-for-lhc-jets#1]
Hi. I'm so sorry to bother you,i see you stared a github project of NonUniformBlurKernelEstimation in paper of Non-uniform Blur Kernel Estimation via Adaptive Basis Decomposition,but now the Pretrained model link is not valid and can't connected author,so can you provide a new link?

**Comment by mackostya** [comment]
Hi, unfortunately I didn't use their pretrained model, so I can't help with this.

**Comment by panyangh** [comment]
ok.thanks



---Original---
From: "Kostiantyn ***@***.***&gt;
Date: Sun, Sep 25, 2022 00:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mackostya/ml-for-lhc-jets] Hi. I'm so sorry to bother you,i hopeyou can share me a Pretrained model link.but,in your code ofNonUniformBlurKernelEstimation ,your Pretrained model link is not valid, canyou provide a new link? (Issue #1)




 
Hi, unfortunately I didn't use their pretensioned model, so I can't help with this.
